server:
  port: 8081
  context-path: /springboot
  
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://192.168.2.103:3306/project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root!@#
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  dubbo:
    application:
      id: project-dubbo-consumer
      name: project-dubbo-consumer
    registry:
      address: zookeeper://192.168.2.103:2181
    protocol:
      port: 20800
      name: dubbo
    #redis配置
  redis:
    host: 192.168.2.103
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.entry 
  


